[project]
name = "shell-commands-emulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "tabulate>=0.9.0",
    "typer>=0.20.1",
]
